
package org.bcsm.tokenclient.ui.phone;

import org.bcsm.tokenclient.ui.ICommonUI;

import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevPasswordField;
import com.xdev.ui.XdevTextArea;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevUpload;
import com.xdev.ui.XdevView;

public class MainView extends XdevView implements ICommonUI {

	/**
	 * 
	 */
	public MainView() {
		super();
		this.initUI();

		//LS TODO
//		uistate.txtNode = this.txtNode;
//		uistate.btnConnect = this.btnConnect;
//		uistate.uploadWalletfile = this.uploadWalletfile;
//		uistate.txtPassword = this.txtPassword;
//		uistate.btnLogin = this.btnLogin;
//		uistate.txtSmartContract = this.txtSmartContract;
//		uistate.btnSubscribeEvents = this.btnSubscribeEvents;
//		uistate.btnLoadContract = this.btnLoadContract;
//		uistate.btnGetTokens = this.btnGetTokens;
//		uistate.cbLogTransactionReceipt = this.cbLogTransactionReceipt;
//		uistate.txtLog = this.txtLog;
//
//		uistate.lblBalance = this.lblBalance;
//		uistate.txtFromAddress = this.txtFromAddress;
//		uistate.txtToAddress = this.txtToAddress;
//		uistate.txtValue = this.txtValue;
//		uistate.btnTransferTokens = this.btnTransferTokens;
//		uistate.cbFromOwnAddress = this.cbFromOwnAddress;
//
//		uistate.txtSecret = this.txtSecret;
//		uistate.btnSetSecret = this.btnSetSecret;
//		uistate.txtNewMember = this.txtNewMember;
//		uistate.btnAddMember = this.btnAddMember;
		
		init ();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #btnConnext}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnConnext_buttonClick(final Button.ClickEvent event) {
		btnConnect_buttonClick_(event);
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #btnGetTokens}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnGetTokens_buttonClick(final Button.ClickEvent event) {
		btnGetTokens_buttonClick_(event);
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.txtNode = new XdevTextField();
		this.btnConnext = new XdevButton();
		this.uploadWalletfile = new XdevUpload();
		this.txtPassword = new XdevPasswordField();
		this.txtSmartContract = new XdevTextField();
		this.btnEventsSubscribe = new XdevButton();
		this.btnGetTokens = new XdevButton();
		this.txtLog = new XdevTextArea();
	
		this.gridLayout.setAutoFill(XdevGridLayout.AutoFill.HORIZONTAL);
		this.txtNode.setCaption("Node:");
		this.txtNode.setValue("https://ropsten.infura.io/sS899But8ce9sP7plpOl");
		this.btnConnext.setCaption("Connect");
		this.btnConnext.setEnabled(false);
		this.uploadWalletfile.setCaption("Upload wallet file:");
		this.txtPassword.setCaption("Password:");
		this.txtSmartContract.setCaption("Smart Contract:");
		this.txtSmartContract.setEnabled(false);
		this.txtSmartContract.setValue("0xa316e5f639e3224b60198e869d33f621f9bb2979");
		this.btnEventsSubscribe.setCaption("Events subscribe");
		this.btnEventsSubscribe.setEnabled(false);
		this.btnGetTokens.setCaption("Get Tokens");
		this.txtLog.setCaption("Log:");
	
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(8);
		this.txtNode.setWidth(100, Unit.PERCENTAGE);
		this.txtNode.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.txtNode, 0, 0);
		this.gridLayout.setComponentAlignment(this.txtNode, Alignment.BOTTOM_RIGHT);
		this.btnConnext.setWidth(100, Unit.PERCENTAGE);
		this.btnConnext.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.btnConnext, 0, 1);
		this.gridLayout.setComponentAlignment(this.btnConnext, Alignment.BOTTOM_RIGHT);
		this.uploadWalletfile.setWidth(100, Unit.PERCENTAGE);
		this.uploadWalletfile.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.uploadWalletfile, 0, 2);
		this.txtPassword.setWidth(100, Unit.PERCENTAGE);
		this.txtPassword.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.txtPassword, 0, 3);
		this.gridLayout.setComponentAlignment(this.txtPassword, Alignment.BOTTOM_RIGHT);
		this.txtSmartContract.setWidth(100, Unit.PERCENTAGE);
		this.txtSmartContract.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.txtSmartContract, 0, 4);
		this.btnEventsSubscribe.setWidth(100, Unit.PERCENTAGE);
		this.btnEventsSubscribe.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.btnEventsSubscribe, 0, 5);
		this.gridLayout.setComponentAlignment(this.btnEventsSubscribe, Alignment.BOTTOM_RIGHT);
		this.btnGetTokens.setWidth(100, Unit.PERCENTAGE);
		this.btnGetTokens.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.btnGetTokens, 0, 6);
		this.txtLog.setSizeFull();
		this.gridLayout.addComponent(this.txtLog, 0, 7);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(7, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	
		this.btnConnext.addClickListener(event -> this.btnConnext_buttonClick(event));
		this.btnGetTokens.addClickListener(event -> this.btnGetTokens_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton btnConnext, btnEventsSubscribe, btnGetTokens;
	private XdevUpload uploadWalletfile;
	private XdevPasswordField txtPassword;
	private XdevTextArea txtLog;
	private XdevGridLayout gridLayout;
	private XdevTextField txtNode, txtSmartContract;
	// </generated-code>

}
